### Get all ads
GET http://localhost:8080/ads
Content-Type: application/json

### Create a new ad
POST http://localhost:8080/ads
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic carolunas@yandex.ru newPassword

--WebAppBoundary
Content-Disposition: form-data; name="properties"
Content-Type: application/json

{
  "price": 4000,
  "title": "New title4",
  "description": "New content4"
}

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="mto.jpg"
Content-Type: image/jpeg

< mto.jpg

### Get ad by id
GET http://localhost:8080/ads/10
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

### Delete ad by id
DELETE http://localhost:8080/ads/10
Content-Type: application/json
Authorization: Basic carolunas@yandex.ru password

### Update ad by id
PATCH http://localhost:8080/ads/12
Content-Type: application/json
Authorization: Basic carolunas@yandex.ru password

{
  "price": 30000,
  "title": "New title updated111",
  "description": "New content updated222"
}

### Get all ads by autorized user
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic user4@gmail.com user4@gmail.com

### Update an image for ad
PATCH http://localhost:8080/ads/1/image
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic user@gmail.com password

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="mto.jpg"
Content-Type: image/jpeg

< mto.jpg

### Get comments for ad
GET http://localhost:8080/ads/11/comments
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

### Add comment to ad
POST http://localhost:8080/ads/11/comments
Content-Type: application/json
Authorization: Basic user3@gmail.com user3@gmail.com

{
  "text": "Comment text to Ad #11"
}

### Update comment for ad
PATCH http://localhost:8080/ads/11/comments/10
Content-Type: application/json
Authorization: Basic carolunas@yandex.ru password

{
  "text": "Updated Comment text admin"
}

### Delete comment for ad
DELETE http://localhost:8080/ads/9/comments/8
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user3@gmail.com",
  "password": "user3@gmail.com"
}

### Register
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user3@gmail.com",
  "password": "user3@gmail.com",
  "firstName": "User3",
  "lastName": "Dummy3",
  "phone": "+7 (913) 213-55-53",
  "role": "USER"
}

### Get details of an authenticated user
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic carolunas@yandex.ru password

### Update details of an authenticated user
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic carolunas@yandex.ru newPassword

{
  "phone": "+7 (913) 213-55-51",
  "firstName": "Dennis33",
  "lastName": "Carolunas33"
}

### Change password of an authenticated user
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic carolunas@yandex.ru password

{
  "newPassword": "newPassword",
  "currentPassword": "password"
}

### Update an avatar for an authenticated user
PATCH http://localhost:8080/users/me/image
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic user2@gmail.com user2@gmail.com

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="mto.jpg"
Content-Type: image/jpeg

< mto.jpg